# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'AudioplayerWithCuckoo' do

end

target 'AudioplayerWithCuckooTests' do
    
    pod 'Cuckoo',
    :git => 'https://github.com/SwiftKit/Cuckoo.git',
    :branch => 'master'
end

